name: Tests Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare to tests
        run: |
          rm -rf __tests__ package-lock.json
          openssl enc -d -aes-256-ecb -in .github/tests.tar.gz -K 688787D8FF144C502C7F5CFFAAFE2CC588D86079F9DE88304C26B0CB99CE91C6 -iter 7 | tar -xzf - -C ./
      - name: Tests
        run: |
          bash -e ./__tests__/test.sh
      - uses: education/autograding@v1
